### ISSUE TITLE
problems with asym_fgm

### ISSUE THREAD

**Issue by cgroll** [MalteKurz/VineCopulaCPP#1]
I added the copula family in julia with the following formulas:
http://cgroll.github.io/copula_theory/param_cops/Asym_FGM.html

Still, however, I get problems with the `v`-function, which returns values larger than 1. Maybe the cdf formula is without the `-u1-u2` terms that we added?

I guess we should take a deeper look into this at Monday. Just wanted to let you know...

**Comment by MalteKurz** [comment]
Thanks for this issue. Indeed there have been used incorrect formulas for the CDF and the Vfun of the asymmetric FGM copula.

The copula is taken from the book of Nelsen (2006), p. 84 Example 3.16, where I set b=0.

I think the correct formulas are:

CDF: 
$$C(u_{1},u_{2})=u_{1}u_{2} + \theta u_{1}u_{2}(1 - u_{1} - u_{2} + u_{1}u_{2})u_{2}(1 - u_{1})$$ 
(Will be corrected in the PairCopulaCDF.cpp file)

PDF: 
$$c(u_{1},u_{2})=1- \theta (3u_{1}^{2}-4u_{1}+1)u_{2}(3u_{2}-2)$$
(Was correct in the PairCopulaPDF.cpp file)

HFUN:
$$h(u_{1},u_{2}) = u_{1} (1+\theta (1-u_{1})^{2} u_{2} (2-3u_{2}))$$
(Was correct in the PairCopulaHfun.cpp file)

VFUN:
$$v(u_{1},u_{2}) = u_{2} (1+\theta u_{2}(1-u_{2})(3u_{1}^2-4u_{1}+1))$$
(Will be corrected in the PairCopulaHfun.cpp file)
